### ISSUE TITLE
error recovery after error in cartesian_pose_subscriber_example_controller fails

### ISSUE THREAD

**Issue by dschaele** [frdedynamics/franka_ros#7]
when recovering from the error the robot immediately triggers a new error, typically a cartesian motion generator joint vel /acc discontinuity

**Comment by dschaele** [comment]
@MOJOliciousFTW Ideas?

**Comment by dschaele** [comment]
looks like it is a problem when the controller is stopped after an error before the error recovery is run.
seems like the error_recovery action restarts the controller. Since recovering from an error in the pose controller makes the robot move back to start and complete the full trajectory. this is a bit dangerous in this case.

**Comment by dschaele** [comment]
Maybe implement a start flag published on a topic, which is checked by the pose controller on start-up? don't know if it would disturb the controller when it is checked in each iteration in update.

**Comment by MOJOliciousFTW** [comment]
weekend! :) have you already gone through Franka forums?

**Comment by MOJOliciousFTW** [comment]
is this what moves the robot back to start, which is not desired on error recovery? https://github.com/frdedynamics/franka_ros/blob/1622c795e5390b48460427357ac76941fa22f6c9/franka_example_controllers/src/cartesian_velocity_example_controller.cpp#L49-L67

**Comment by dschaele** [comment]
No, in the `cartesian_pose_subscriber_example_controller` the motion is loaded while initializing the controller, and then executed from start to end without external influence.  quite the opposite to the `cartesian_impedance_example_controller` which subscribes to the `/equilibrium_pose` topic and thus gets its set points from the outside. this is not possible for the pose_controller, since it is very sensitive to acceleration discontinuities. thats why the complete motion is looped through inside the contoller node.
Now, the `error_recovery` resets the last active controller, and due to the way i implemented the pose_controller, it moves back to start since its just re-starting the motion automatically.

The moving back to start is expected behaviour in this case - I was just not aware at first that the controller gets reset.
I will open a new issue on the main problem which is that in some cases the robot immediately hits a new error when recovered from the last one

**Comment by dschaele** [comment]
See #9
